services:

  crm:
    build: .
    restart: always
    depends_on:
    - db
    ports:
      - 8080:8080
    volumes:
      # Bind-mount settings for quick updates without rebuilds
      - ./settings.py:/app/webcrm/settings.py:ro

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Secret5555
      MYSQL_DATABASE: crm_db
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crmpass
    # (this is just an example, not intended to be a production configuration)
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data:/var/lib/mysql
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8078:8080

volumes:
  mysql_db_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.172.27.9,nolock,soft,rw,proto=tcp,vers=3"
      device: ":/mnt/mysql-data"