apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-crm.fullname" . }}-mysql-secret
  labels:
    {{- include "django-crm.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
type: Opaque
data:
  root-password: {{ .Values.mysql.config.rootPassword | b64enc }}
  password: {{ .Values.mysql.config.password | b64enc }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-crm.fullname" . }}-settings
  labels:
    {{- include "django-crm.labels" . | nindent 4 }}
    app.kubernetes.io/component: crm
data:
  settings.py: |
    import sys
    from pathlib import Path
    from datetime import datetime as dt
    from django.utils.translation import gettext_lazy as _

    from crm.settings import *          # NOQA
    from common.settings import *       # NOQA
    from tasks.settings import *        # NOQA
    from voip.settings import *         # NOQA
    from .datetime_settings import *    # NOQA

    # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
    BASE_DIR = Path(__file__).resolve().parent.parent

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = '{{ .Values.crm.settings.secretKey }}'

    # Add your hosts to the list.
    ALLOWED_HOSTS = {{ .Values.crm.settings.allowedHosts | toJson }}
    CSRF_TRUSTED_ORIGINS = {{ .Values.crm.settings.csrfTrustedOrigins | toJson }}

    # Database
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'PORT': '3306',
            'NAME': '{{ .Values.mysql.config.database }}',
            'USER': '{{ .Values.mysql.config.user }}',
            'PASSWORD': '{{ .Values.mysql.config.password }}',
            'HOST': '{{ include "django-crm.fullname" . }}-mysql',
        }
    }

    EMAIL_HOST = '<specify host>'
    EMAIL_HOST_PASSWORD = '<specify password>'
    EMAIL_HOST_USER = 'crm@example.com'
    EMAIL_PORT = 587
    EMAIL_SUBJECT_PREFIX = 'CRM: '
    EMAIL_USE_TLS = True

    SERVER_EMAIL = 'test@example.com'
    DEFAULT_FROM_EMAIL = 'test@example.com'

    ADMINS = [("<Admin1>", "<admin1_box@example.com>")]

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = {{ .Values.crm.settings.debug }}

    FORMS_URLFIELD_ASSUME_HTTPS = True

    # Internationalization
    LANGUAGE_CODE = 'en'
    LANGUAGES = [
        ('ar', 'Arabic'),
        ('cs', 'Czech'),
        ('de', 'German'),
        ('el', 'Greek'),
        ('en', 'English'),
        ('es', 'Spanish'),
        ('fr', 'French'),
        ('he', 'Hebrew'),
        ('hi', 'Hindi'),
        ('id', 'Indonesian'),
        ('it', 'Italian'),
        ('ja', 'Japanese'),
        ('ko', 'Korean'),
        ('nl', 'Nederlands'),
        ('pl', 'Polish'),
        ('pt-br', 'Portuguese'),
        ('ro', 'Romanian'),
        ('ru', 'Russian'),
        ('tr', 'Turkish'),
        ('uk', 'Ukrainian'),
        ('vi', 'Vietnamese'),
        ('zh-hans', 'Chinese'),
    ]

    TIME_ZONE = 'UTC'
    USE_I18N = True
    USE_TZ = True

    LOCALE_PATHS = [
        BASE_DIR / 'locale',
    ]

    LOGIN_URL = '/admin/login/'

    # Application definition
    INSTALLED_APPS = [
        'django.contrib.sites',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'crm.apps.CrmConfig',
        'massmail.apps.MassmailConfig',
        'analytics.apps.AnalyticsConfig',
        'help',
        'tasks.apps.TasksConfig',
        'chat.apps.ChatConfig',
        'voip',
        'common.apps.CommonConfig',
        'settings'
    ]

    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.locale.LocaleMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'common.utils.usermiddleware.UserMiddleware'
    ]

    ROOT_URLCONF = 'webcrm.urls'

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [BASE_DIR / 'templates'],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

    WSGI_APPLICATION = 'webcrm.wsgi.application'

    # Password validation
    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]

    # Static files (CSS, JavaScript, Images)
    STATIC_URL = 'static/'
    STATIC_ROOT = BASE_DIR / 'static'

    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'

    FIXTURE_DIRS = ['tests/fixtures']

    MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

    SITE_ID = 1

    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_PRELOAD = False
    X_FRAME_OPTIONS = "SAMEORIGIN"

    DJANGO_RUNSERVER_HIDE_WARNING = True

    # ---- CRM settings ---- #
    SECRET_CRM_PREFIX = '123/'
    SECRET_ADMIN_PREFIX = '456-admin/'
    SECRET_LOGIN_PREFIX = '789-login/'

    CRM_IP = "127.0.0.1"
    CRM_REPLY_TO = ["'Do not reply' <crm@example.com>"]
    NOT_ALLOWED_EMAILS = []

    APP_ON_INDEX_PAGE = [
        'tasks', 'crm', 'analytics',
        'massmail', 'common', 'settings'
    ]
    MODEL_ON_INDEX_PAGE = {
        'tasks': {
            'app_model_list': ['Task', 'Memo']
        },
        'crm': {
            'app_model_list': [
                'Request', 'Deal', 'Lead', 'Company',
                'CrmEmail', 'Payment', 'Shipment'
            ]
        },
        'analytics': {
            'app_model_list': [
                'IncomeStat', 'RequestStat'
            ]
        },
        'massmail': {
            'app_model_list': [
                'MailingOut', 'EmlMessage'
            ]
        },
        'common': {
            'app_model_list': [
                'UserProfile', 'Reminder'
            ]
        },
        'settings': {
            'app_model_list': [
                'PublicEmailDomain', 'StopPhrase'
            ]
        }
    }

    VAT = 0

    CLIENT_ID = ''
    CLIENT_SECRET = ''
    OAUTH2_DATA = {
        'smtp.gmail.com': {
            'scope': "https://mail.google.com/",
            'accounts_base_url': 'https://accounts.google.com',
            'auth_command': 'o/oauth2/auth',
            'token_command': 'o/oauth2/token',
        }
    }
    REDIRECT_URI = ''

    GOOGLE_RECAPTCHA_SITE_KEY = ''
    GOOGLE_RECAPTCHA_SECRET_KEY = ''

    GEOIP = False
    GEOIP_PATH = MEDIA_ROOT / 'geodb'

    SHOW_USER_CURRENT_TIME_ZONE = False
    NO_NAME_STR = _('Untitled')

    LOAD_EXCHANGE_RATE = False
    LOADING_EXCHANGE_RATE_TIME = "6:30"
    LOAD_RATE_BACKEND = ""

    MARK_PAYMENTS_THROUGH_REP = False

    SITE_TITLE = 'CRM'
    ADMIN_HEADER = "ADMIN"
    ADMIN_TITLE = "CRM Admin"
    INDEX_TITLE = _('Main Menu')

    MAILING = True

    COPYRIGHT_STRING = f"Django-CRM. Copyright (c) {dt.now().year}"
    PROJECT_NAME = "Django-CRM"
    PROJECT_SITE = "https://github.com/DjangoCRM/django-crm/"

    TESTING = sys.argv[1:2] == ['test']
    if TESTING:
        SECURE_SSL_REDIRECT = False
        LANGUAGE_CODE = 'en'
        LANGUAGES = [('en', ''), ('uk', '')]
