{{- if .Values.crm.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-crm.fullname" . }}-crm
  labels:
    {{- include "django-crm.labels" . | nindent 4 }}
    app.kubernetes.io/component: crm
spec:
  replicas: {{ .Values.crm.replicaCount }}
  selector:
    matchLabels:
      {{- include "django-crm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: crm
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "django-crm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: crm
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "django-crm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.crm.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "django-crm.crm.image" . }}
          imagePullPolicy: {{ .Values.crm.image.pullPolicy | default .Values.global.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.crm.service.targetPort }}
              protocol: TCP
          env:
            {{- toYaml .Values.crm.env | nindent 12 }}
          volumeMounts:
            - name: settings
              mountPath: /app/webcrm/settings.py
              subPath: settings.py
              readOnly: true
          livenessProbe:
            httpGet:
              path: /admin/login/
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /admin/login/
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.crm.resources | nindent 12 }}
      volumes:
        - name: settings
          configMap:
            name: {{ include "django-crm.fullname" . }}-settings
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
